### ISSUE TITLE
Error: Received unknown parameter: at_period_end

### ISSUE THREAD

**Issue by gotsteez** [adi87/stripe-all-sub-cancel-js#1]
I get ` Error: Received unknown parameter: at_period_end` when I try to cancel a subscription, and this happens for all my subscriptions. This is ran on live mode, not dry mode.

**Comment by adi87** [comment]
@zMrKrabz try upgrading to version 1.1.0 of this lib and see if that fixes your issue? I've also added a new parameter to cancel immediately instead of at the end of the billing cycle (the default). Let me know how that works out
